version: '3.8'

services:
  hangfire-server:
    build:
      context: .
      dockerfile: ./HangfireServerApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"  # Expose the port for the Hangfire dashboard
    networks:
      - hangfire-net

  consoleapp1:
    build:
      context: .
      dockerfile: ./HangfireConsoleApp1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire-server
    networks:
      - hangfire-net

  consoleapp2:
    build:
      context: .
      dockerfile: ./HangfireConsoleApp2/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire-server
    networks:
      - hangfire-net

  consoleapp3:
    build:
      context: .
      dockerfile: ./HangfireConsoleApp3/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - hangfire-server
    networks:
      - hangfire-net

networks:
  hangfire-net:
    driver: bridge
